	 ${leadDetails[0].customerName}
     $:${leadDetails[0].hGroupId}
     $:${leadDetails[0].registrationNo}
     $:${leadDetails[0].custPan}
     	 $:${leadDetails[0].businessSegment}
     $:${leadDetails[0].lbxIndustry}
     $:${leadDetails[0].lbxSubIndustry}
     $:${leadDetails[0].customerType}
      $:${leadDetails[0].contitutionCode}
     $:${leadDetails[0].firstName}
     $:${leadDetails[0].lastName}
     $:${leadDetails[0].custDOB}
     	 $:${leadDetails[0].address1}
     $:${leadDetails[0].address2}
     $:${leadDetails[0].addresstype}
     $:${leadDetails[0].noOfYears}
        	 $:${leadDetails[0].pincode}
     $:${leadDetails[0].txtCountryCode}
     $:${leadDetails[0].txtStateCode}
     $:${leadDetails[0].txtDistCode}
        $:${leadDetails[0].email}
 $:${leadDetails[0].groupName}
			 $:${leadDetails[0].country}
			 $:${leadDetails[0].dist}
			 $:${leadDetails[0].state}
			 $:${leadDetails[0].industry}
			 $:${leadDetails[0].subIndustry}
			 $:${leadDetails[0].relationshipSince}
			 $:${leadDetails[0].phoneOff}
			  $:${leadDetails[0].fatherName}
			  $:${leadDetails[0].aadhaar}
			  $:${leadDetails[0].voterId}
			  $:${leadDetails[0].passport}
			   $:${leadDetails[0].genderIndividual}
			          $:${leadDetails[0].address3}
			 $:${leadDetails[0].middleName}
			 $:${leadDetails[0].landmark}
			          $:${leadDetails[0].groupType}
	