/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.cm.actions;

import java.util.ArrayList;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.validator.DynaValidatorForm;
import com.cm.dao.KnockOffDAO;
import com.cm.vo.KnockOffSearchVO;
import com.connect.CommonFunction;
import com.connect.DaoImplInstanceFactory;
import com.login.dao.UserSessionCheck;
import com.login.roleManager.UserObject;

/** 
 * MyEclipse Struts
 * Creation date: 07-13-2011
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class KnockOffSearchBehindAction extends DispatchAction {
	private static final Logger logger = Logger.getLogger(KnockOffSearchBehindAction.class.getName());
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward knockOffMakerSearch(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws Exception {
		logger.info("Inside KnockOffSearchBehindAction.....knockOffMakerSearch");
		
		HttpSession session = request.getSession();
		boolean flag=false;
		UserObject userobj=(UserObject)session.getAttribute("userobject");
		String userId="";
		String branchId="";
		if(userobj!=null)
		{
			userId=userobj.getUserId();
			branchId=userobj.getBranchId();
		}else{
			logger.info("in  knockOffMakerSearch method of KnockOffSearchBehindAction action the session is out----------------");
			return mapping.findForward("sessionOut");
		}
		Object sessionId = session.getAttribute("sessionID");

		//for check User session start
		ServletContext context = getServlet().getServletContext();
		String strFlag="";	
		
		if(sessionId!=null)
		{
			strFlag = UserSessionCheck.checkSameUserSession(userobj,sessionId.toString(),"",request);
		}
		
		logger.info("strFlag .............. "+strFlag);
		if(!strFlag.equalsIgnoreCase(""))
		{
			if(strFlag.equalsIgnoreCase("sameUserSession"))
			{
				context.removeAttribute("msg");
				context.removeAttribute("msg1");
			}
			else if(strFlag.equalsIgnoreCase("BODCheck"))
			{
				context.setAttribute("msg", "B");
			}
			return mapping.findForward("logout");
		}
		
		session.removeAttribute("knockOffAuthorValues");
		session.removeAttribute("loanDataListR");
		session.removeAttribute("loanDataListP");
		session.removeAttribute("knockOffSearchList");
		session.removeAttribute("loanId");
		session.removeAttribute("knockOffID");
		session.removeAttribute("totalR");
	    session.removeAttribute("totalP");
	    session.removeAttribute("showdetails");
	    KnockOffSearchVO vo= new KnockOffSearchVO();
		
		int currentPageLink = 0;
		if(request.getParameter("d-49520-p")==null || request.getParameter("d-49520-p").equalsIgnoreCase("0"))
		{
			currentPageLink=1;
		}
		else
		{
			currentPageLink =Integer.parseInt(request.getParameter("d-49520-p"));
		}
		logger.info("current page link ................ "+request.getParameter("d-49520-p"));
		vo.setCurrentPageLink(currentPageLink);
		String type="P";
		DynaValidatorForm KnockOffSearchDynaValidatorForm = (DynaValidatorForm)form;
		org.apache.commons.beanutils.BeanUtils.copyProperties(vo,KnockOffSearchDynaValidatorForm);
		if(CommonFunction.checkNull(vo.getReportingToUserId()).equalsIgnoreCase(""))
		{ 
			vo.setReportingToUserId(userId);
		   //logger.info("When user id is not selected by the user:::::"+userId);
		}
		logger.info("user Id:::::"+vo.getReportingToUserId());
		vo.setStage(type);
		vo.setBranchId(branchId);
		vo.setUserId(userId);
		KnockOffDAO service=(KnockOffDAO)DaoImplInstanceFactory.getDaoImplInstance(KnockOffDAO.IDENTITY);
		logger.info("Implementation class: "+service.getClass()); 
		vo.setLbxLoanNoHID("");
		vo.setCustomerName("");
	    ArrayList<KnockOffSearchVO> knockOffSearchList = service.searchKnockOffData(vo,type);
	    
	    if(knockOffSearchList.size()==0)
		{
			request.setAttribute("message","N");
			if(type.equalsIgnoreCase("P"))
			{
				request.setAttribute("knockOffMakerSearch","knockOffMakerSearch");
				request.setAttribute("knockOffSearchList","knockOffSearchList");
			}
			
			else if(type.equalsIgnoreCase("F"))
			{
				request.setAttribute("knockOffAuthorSearch","knockOffAuthorSearch");
			
			}
		}
		else
		{
			if(type.equalsIgnoreCase("P"))
			{
				request.setAttribute("knockOffMakerSearch","knockOffMakerSearch");
				request.setAttribute("knockOffSearchList","knockOffSearchList");
				request.setAttribute("list", knockOffSearchList);
			}
			
			else if(type.equalsIgnoreCase("F"))
			{
				request.setAttribute("knockOffAuthorSearch","knockOffAuthorSearch");
				request.setAttribute("knockOffSearchList", knockOffSearchList);
				
			}
		}
		return mapping.findForward("knockOffMakerSearch");
	}
	
	public ActionForward knockOffAuthorSearch(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)throws Exception {
		logger.info("Inside KnockOffSearchBehindAction.....knockOffAuthorSearch");
		
		HttpSession session = request.getSession();
		boolean flag=false;
		UserObject userobj=(UserObject)session.getAttribute("userobject");
		
		String userId="";
		String branchId="";
		if(userobj!=null)
		{
			userId=userobj.getUserId();
			branchId=userobj.getBranchId();
		}else{
			logger.info("in knockOffAuthorSearch method of KnockOffSearchBehindAction  action the session is out----------------");
			return mapping.findForward("sessionOut");
		}
		Object sessionId = session.getAttribute("sessionID");
		//for check User session start
		ServletContext context = getServlet().getServletContext();
		String strFlag="";	
		
		if(sessionId!=null)
		{
			strFlag = UserSessionCheck.checkSameUserSession(userobj,sessionId.toString(),"",request);
		}
		
		logger.info("strFlag .............. "+strFlag);
		if(!strFlag.equalsIgnoreCase(""))
		{
			if(strFlag.equalsIgnoreCase("sameUserSession"))
			{
				context.removeAttribute("msg");
				context.removeAttribute("msg1");
			}
			else if(strFlag.equalsIgnoreCase("BODCheck"))
			{
				context.setAttribute("msg", "B");
			}
			return mapping.findForward("logout");
		}

		session.removeAttribute("knockOffAuthorValues");
		session.removeAttribute("loanDataListR");
		session.removeAttribute("loanDataListP");
		session.removeAttribute("knockOffSearchList");
		session.removeAttribute("loanId");
		session.removeAttribute("knockOffID");
		session.removeAttribute("totalR");
	    session.removeAttribute("totalP");
	    session.removeAttribute("showdetails");
	    
	    KnockOffSearchVO vo= new KnockOffSearchVO();
		
		int currentPageLink = 0;
		if(request.getParameter("d-49520-p")==null || request.getParameter("d-49520-p").equalsIgnoreCase("0"))
		{
			currentPageLink=1;
		}
		else
		{
			currentPageLink =Integer.parseInt(request.getParameter("d-49520-p"));
		}
		logger.info("current page link ................ "+request.getParameter("d-49520-p"));
		vo.setCurrentPageLink(currentPageLink);
		String type="F";
		DynaValidatorForm KnockOffSearchDynaValidatorForm = (DynaValidatorForm)form;
		org.apache.commons.beanutils.BeanUtils.copyProperties(vo,KnockOffSearchDynaValidatorForm);

		if(CommonFunction.checkNull(vo.getReportingToUserId()).equalsIgnoreCase(""))
				{ 
					vo.setReportingToUserId(userId);
				   //logger.info("When user id is not selected by the user:::::"+userId);
				}
				logger.info("user Id:::::"+vo.getReportingToUserId());
		vo.setStage(type);
		vo.setBranchId(branchId);
		vo.setUserId(userId);
		vo.setLbxLoanNoHID("");
		vo.setCustomerName("");
		KnockOffDAO service=(KnockOffDAO)DaoImplInstanceFactory.getDaoImplInstance(KnockOffDAO.IDENTITY);
		logger.info("Implementation class: "+service.getClass()); 
	    ArrayList<KnockOffSearchVO> knockOffSearchList = service.searchKnockOffData(vo,type);
	    
	    if(knockOffSearchList.size()==0)
		{
			request.setAttribute("message","N");
			if(type.equalsIgnoreCase("P"))
			{
				request.setAttribute("knockOffMakerSearch","knockOffMakerSearch");
				request.setAttribute("knockOffSearchList","knockOffSearchList");
			}
			
			else if(type.equalsIgnoreCase("F"))
			{
				request.setAttribute("knockOffAuthorSearch","knockOffAuthorSearch");
				request.setAttribute("knockOffSearchList", "knockOffSearchList");
			}
		}
		else
		{
			if(type.equalsIgnoreCase("P"))
			{
				request.setAttribute("knockOffMakerSearch","knockOffMakerSearch");
				request.setAttribute("knockOffSearchList","knockOffSearchList");
				request.setAttribute("list", knockOffSearchList);
			}
			
			else if(type.equalsIgnoreCase("F"))
			{
				request.setAttribute("knockOffAuthorSearch","knockOffAuthorSearch");
				request.setAttribute("knockOffSearchList", "knockOffSearchList");
				request.setAttribute("list", knockOffSearchList);
			}
		}
		return mapping.findForward("knockOffAuthorSearch");
	}
}